CREATE TABLE PUBLIC.TYPES
(ID IDENTITY NOT NULL,
NAME VARCHAR_IGNORECASE(8) DEFAULT '' NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME));
CREATE TABLE PUBLIC.OFFSETS
(START_OFFSET BIGINT NOT NULL,
END_OFFSET BIGINT DEFAULT -1 NOT NULL,
TYPE_ID BIGINT NOT NULL,
ENDS_IN_PADDED_CLUSTER BOOLEAN DEFAULT false NOT NULL,
PRIMARY KEY (START_OFFSET),
foreign key (TYPE_ID) references TYPES(ID));
--ALTER TABLE OFFSETS ADD COLUMN ENDS_IN_PADDED_CLUSTER BOOLEAN DEFAULT false NOT NULL 
