CREATE TABLE PUBLIC.TYPES
(ID IDENTITY NOT NULL,
NAME VARCHAR_IGNORECASE(8) DEFAULT '' NOT NULL,
PRIMARY KEY (ID),
UNIQUE (NAME));
CREATE TABLE PUBLIC.OFFSETS
(START_OFFSET BIGINT NOT NULL,
END_OFFSET BIGINT DEFAULT -1 NOT NULL,
TYPE_ID BIGINT NOT NULL,
ENDS_IN_PADDED_CLUSTER BOOLEAN DEFAULT false NOT NULL,
PRIMARY KEY (START_OFFSET),
foreign key (TYPE_ID) references TYPES(ID));
--ALTER TABLE OFFSETS ADD COLUMN ENDS_IN_PADDED_CLUSTER BOOLEAN DEFAULT false NOT NULL 
CREATE TABLE PUBLIC.NOTES
(OFFSET_ID BIGINT NOT NULL, 
NOTE VARCHAR,
UNIQUE(START_OFFSET, NOTE),
foreign key (OFFSET_ID) references OFFSETS(START_OFFSET));
CREATE TABLE PUBLIC.NOTES
(OFFSET_ID BIGINT NOT NULL, 
NOTE VARCHAR,
UNIQUE(OFFSET_ID, NOTE),
foreign key (OFFSET_ID) references OFFSETS(START_OFFSET));
CREATE TABLE PUBLIC.MOZ_CACHE_URLS
(ID IDENTITY NOT NULL,
URL VARCHAR(4096) NOT NULL, 
PRIMARY KEY (ID),
UNIQUE(URL));
CREATE TABLE MOZ_CACHE_ASSOC
(OFFSET_ID BIGINT NOT NULL,
MOZ_CACHE_URL_ID BIGINT NOT NULL,
PRIMARY KEY (OFFSET_ID),
foreign key (OFFSET_ID) references OFFSETS(START_OFFSET),
foreign key (MOZ_CACHE_URL_ID) references MOZ_CACHE_URLS(ID)
);
CREATE TABLE PUBLIC.ZEROED_OFFSET_RANGES
(START_OFFSET BIGINT NOT NULL,
LENGTH BIGINT NOT NULL,
PRIMARY KEY(START_OFFSET));
CREATE TABLE PUBLIC.READ_ERROR_RANGES
(START_OFFSET BIGINT NOT NULL,
LENGTH BIGINT NOT NULL,
PRIMARY KEY(START_OFFSET));
CREATE TABLE PUBLIC.READ_ERROR_MESSAGES
(ID IDENTITY NOT NULL,
MESSAGE VARCHAR_IGNORECASE(512),
PRIMARY KEY(ID),
UNIQUE(MESSAGE));
CREATE TABLE PUBLIC.READ_ERROR_RANGES_MESSAGES
(READ_ERROR_RANGES_ID BIGINT NOT NULL,
READ_ERROR_MESSAGE_ID BIGINT NOT NULL,
PRIMARY KEY (READ_ERROR_RANGES_ID),
FOREIGN KEY (READ_ERROR_RANGES_ID) references READ_ERROR_RANGES(START_OFFSET),
FOREIGN KEY (READ_ERROR_MESSAGE_ID) references READ_ERROR_MESSAGES(ID));

